apiVersion: addons.kyma-project.io/v1alpha1
kind: AddonsConfiguration
metadata:
  name: sbu-test
spec:
  reprocessRequest: 0
  repositories:
    - url: https://github.com/kyma-project/addons/releases/download/0.11.0/index-testing.yaml
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: sbu-test
spec:
  serviceClassExternalName: redis
  servicePlanExternalName: micro
  parameters:
    imagePullPolicy: Always
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: sbu-test
spec:
  instanceRef:
    name: sbu-test
